services:
  portal:
    image: maschtz22/agrovale-portal:1.0-26128314
    ports:
      - "8014:80"
    restart: unless-stopped
    networks:
      - agrovale

  blog:
    image: wordpress:latest
    ports:
      - "9014:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - wp_dados:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - agrovale

  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - db_dados:/var/lib/mysql
    restart: unless-stopped
    networks:
      - agrovale

volumes:
  wp_dados:
  db_dados:

networks:
  agrovale: